export const GET_PRICES = 'GET_PRICES';
export const GET_PRICES_COMPLETE = 'GET_PRICES_COMPLETE';
export const GET_PRICES_FAILED = 'GET_PRICES_FAILED';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_COMPANY_COMPLETE = 'UPDATE_COMPANY_COMPLETE';
export const UPDATE_COMPANY_FAILED = 'UPDATE_COMPANY_FAILED';
